baseURL = 'https://artware.be/'
defaultContentLanguage = 'nl'
defaultContentLanguageInSubdir = false
title = 'ARTware - Keramiek - Lieve De Schutter'

[languages]
  [languages.nl]
    languageCode = 'nl-be'
    languageName = 'Nederlands'
    title = 'ARTware - Keramiek - Lieve De Schutter'
    weight = 1
  [languages.en]
    languageCode = 'en'
    languageName = 'English'
    title = 'ARTware - Ceramics - Lieve De Schutter'
    weight = 2

[params]
gaID = "G-97J7MR4Z70"

[taxonomies]


[caches]
  [caches.images]
    dir = ':cacheDir/images'
