baseURL = 'https://artware.be/'
languageCode = 'nl-be'
title = 'ARTware - Keramiek - Lieve De Schutter'

[params]
logo = './images/logo.png'

[taxonomies]


[caches]
  [caches.images]
    dir = ':cacheDir/images'
